version: '3.8'

services:
  web:
    # We take the Dockerfile from the app directory
    build: ./app
    # We start the test server
    command: python manage.py runserver 0.0.0.0:8000
    # where the data from the app directory will be placed
    volumes:
      - ./app/:/usr/src/app/
    # Opening port 8000 inside and outside
    ports:
      - 8000:8000
    # The file containing the variables for the container
    env_file:
      - ./.env.dev
  db:
    # The image and version of the base that we will use
    image: postgres:12.0-alpine
    # External volume and the place where it will be mounted inside the container
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      # Credentials that can be overridden
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db

volumes:
  postgres_volume:
