version: '3.8'

services:
  web:
    # We take the Dockerfile from the app directory
    build:
        context: ./app
        dockerfile: Dockerfile.prod
    # Start the gunicorn server
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    # Opening port 8000 outward
    expose:
            - 8000
    # Connect static and media files
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./.env.prod
    # We are waiting for the launch of the db container
    depends_on:
      - db
  db:
    # The image and version of the base that we will use
    image: postgres:12.0-alpine
    # External volume and the place where it will be connected inside
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    # Connect static and media files
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web


volumes:
  postgres_volume:
  static_volume:
  media_volume:
